# action.yml
name: "yamlfix"
description: "Check, lint and fix YAML files"
author: "Davi Mello"

branding:
  color: "blue"
  icon: "check-circle"

inputs:
  args:
    description: "The file or directory to check"
    required: false
    default: "."

runs:
  using: "docker"
  image: "Dockerfile"

  args:
    - ${{ inputs.args }}
