# action.yml
name: "yamlfix"
description: "Check, lint and fix YAML files"
inputs:
  file-path:
    description: "The file or directory to check"
    required: false
    default: "."

runs:
  using: "docker"
  image: "Dockerfile"

  args:
    - ${{ file-path }}
